# Generated by Django 4.1.5 on 2023-01-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='telf',
            field=models.IntegerField(),
        ),
    ]
