# Generated by Django 4.1.5 on 2023-01-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_alumno_cedula_alter_alumno_telf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
