# Generated by Django 4.1.5 on 2023-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_rename_correo_alumno_email_rename_name_alumno_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestro',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='maestro',
            old_name='name',
            new_name='f_name',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='telf',
        ),
        migrations.AddField(
            model_name='maestro',
            name='l_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro',
            name='username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
